[2024-11-20T10:15:10.643+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T10:15:10.734+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T03:14:58.872145+00:00 [queued]>
[2024-11-20T10:15:10.764+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T03:14:58.872145+00:00 [queued]>
[2024-11-20T10:15:10.768+0700] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-20T10:15:10.944+0700] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_twitter_task> on 2024-11-20 03:14:58.872145+00:00
[2024-11-20T10:15:11.006+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'scrape_twitter', 'scrape_twitter_task', 'manual__2024-11-20T03:14:58.872145+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/scrape_twitter_dag.py', '--cfg-path', '/tmp/tmpwl4xod5b']
[2024-11-20T10:15:11.012+0700] {standard_task_runner.py:105} INFO - Job 17: Subtask scrape_twitter_task
[2024-11-20T10:15:11.019+0700] {logging_mixin.py:190} WARNING - /home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=102593) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-20T10:15:11.022+0700] {standard_task_runner.py:72} INFO - Started process 102883 to run task
[2024-11-20T10:15:11.375+0700] {task_command.py:467} INFO - Running <TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T03:14:58.872145+00:00 [running]> on host fabian4819-VirtualBox
[2024-11-20T10:15:11.998+0700] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrape_twitter' AIRFLOW_CTX_TASK_ID='scrape_twitter_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T03:14:58.872145+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T03:14:58.872145+00:00'
[2024-11-20T10:15:12.001+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T10:15:12.002+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T10:15:12.004+0700] {logging_mixin.py:190} INFO - Current task name:scrape_twitter_task state:running start_date:2024-11-20 03:15:10.735958+00:00
[2024-11-20T10:15:12.005+0700] {logging_mixin.py:190} INFO - Dag name:scrape_twitter and current dag run status:running
[2024-11-20T10:15:12.008+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T10:15:13.375+0700] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow/dags/scrape_twitter_dag.py", line 40, in run_scrape_twitter
    scrape_twitter(search_term)  # Panggil fungsi dari scrapping-twitter.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/notebooks/scrapping-twitter.py", line 20, in scrape_twitter
    driver = webdriver.Chrome()
             ^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
    self.start_session(capabilities)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/fabian4819/.cache/selenium/chrome/linux64/131.0.6778.85/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5f064f34e31a <unknown>
#1 0x5f064ee646e0 <unknown>
#2 0x5f064ee9bdc8 <unknown>
#3 0x5f064ee97926 <unknown>
#4 0x5f064eee36f6 <unknown>
#5 0x5f064eee2d46 <unknown>
#6 0x5f064eed7203 <unknown>
#7 0x5f064eea5cc0 <unknown>
#8 0x5f064eea6c9e <unknown>
#9 0x5f064f31bd0b <unknown>
#10 0x5f064f31fc92 <unknown>
#11 0x5f064f308b3c <unknown>
#12 0x5f064f320807 <unknown>
#13 0x5f064f2ee0df <unknown>
#14 0x5f064f33d578 <unknown>
#15 0x5f064f33d740 <unknown>
#16 0x5f064f34d196 <unknown>
#17 0x76a9d349ca94 <unknown>
#18 0x76a9d3529c3c <unknown>

[2024-11-20T10:15:13.483+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T10:15:13.486+0700] {logging_mixin.py:190} INFO - Task start:2024-11-20 03:15:10.735958+00:00 end:2024-11-20 03:15:13.482033+00:00 duration:2.746075
[2024-11-20T10:15:13.487+0700] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_twitter_task> dag:<DAG: scrape_twitter> dagrun:<DagRun scrape_twitter @ 2024-11-20 03:14:58.872145+00:00: manual__2024-11-20T03:14:58.872145+00:00, state:running, queued_at: 2024-11-20 03:14:58.923418+00:00. externally triggered: True>
[2024-11-20T10:15:13.488+0700] {logging_mixin.py:190} INFO - Failure caused by Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/fabian4819/.cache/selenium/chrome/linux64/131.0.6778.85/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5f064f34e31a <unknown>
#1 0x5f064ee646e0 <unknown>
#2 0x5f064ee9bdc8 <unknown>
#3 0x5f064ee97926 <unknown>
#4 0x5f064eee36f6 <unknown>
#5 0x5f064eee2d46 <unknown>
#6 0x5f064eed7203 <unknown>
#7 0x5f064eea5cc0 <unknown>
#8 0x5f064eea6c9e <unknown>
#9 0x5f064f31bd0b <unknown>
#10 0x5f064f31fc92 <unknown>
#11 0x5f064f308b3c <unknown>
#12 0x5f064f320807 <unknown>
#13 0x5f064f2ee0df <unknown>
#14 0x5f064f33d578 <unknown>
#15 0x5f064f33d740 <unknown>
#16 0x5f064f34d196 <unknown>
#17 0x76a9d349ca94 <unknown>
#18 0x76a9d3529c3c <unknown>
[2024-11-20T10:15:13.488+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_twitter, task_id=scrape_twitter_task, run_id=manual__2024-11-20T03:14:58.872145+00:00, execution_date=20241120T031458, start_date=20241120T031510, end_date=20241120T031513
[2024-11-20T10:15:13.556+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T10:15:13.565+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task scrape_twitter_task (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/fabian4819/.cache/selenium/chrome/linux64/131.0.6778.85/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5f064f34e31a <unknown>
#1 0x5f064ee646e0 <unknown>
#2 0x5f064ee9bdc8 <unknown>
#3 0x5f064ee97926 <unknown>
#4 0x5f064eee36f6 <unknown>
#5 0x5f064eee2d46 <unknown>
#6 0x5f064eed7203 <unknown>
#7 0x5f064eea5cc0 <unknown>
#8 0x5f064eea6c9e <unknown>
#9 0x5f064f31bd0b <unknown>
#10 0x5f064f31fc92 <unknown>
#11 0x5f064f308b3c <unknown>
#12 0x5f064f320807 <unknown>
#13 0x5f064f2ee0df <unknown>
#14 0x5f064f33d578 <unknown>
#15 0x5f064f33d740 <unknown>
#16 0x5f064f34d196 <unknown>
#17 0x76a9d349ca94 <unknown>
#18 0x76a9d3529c3c <unknown>
; 102883)
Traceback (most recent call last):
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow/dags/scrape_twitter_dag.py", line 40, in run_scrape_twitter
    scrape_twitter(search_term)  # Panggil fungsi dari scrapping-twitter.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/notebooks/scrapping-twitter.py", line 20, in scrape_twitter
    driver = webdriver.Chrome()
             ^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
    self.start_session(capabilities)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/fabian4819/.cache/selenium/chrome/linux64/131.0.6778.85/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5f064f34e31a <unknown>
#1 0x5f064ee646e0 <unknown>
#2 0x5f064ee9bdc8 <unknown>
#3 0x5f064ee97926 <unknown>
#4 0x5f064eee36f6 <unknown>
#5 0x5f064eee2d46 <unknown>
#6 0x5f064eed7203 <unknown>
#7 0x5f064eea5cc0 <unknown>
#8 0x5f064eea6c9e <unknown>
#9 0x5f064f31bd0b <unknown>
#10 0x5f064f31fc92 <unknown>
#11 0x5f064f308b3c <unknown>
#12 0x5f064f320807 <unknown>
#13 0x5f064f2ee0df <unknown>
#14 0x5f064f33d578 <unknown>
#15 0x5f064f33d740 <unknown>
#16 0x5f064f34d196 <unknown>
#17 0x76a9d349ca94 <unknown>
#18 0x76a9d3529c3c <unknown>

[2024-11-20T10:15:13.594+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T10:15:13.710+0700] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T10:15:13.715+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
