[2024-11-20T11:07:55.633+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T11:07:55.718+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T04:00:16.632398+00:00 [queued]>
[2024-11-20T11:07:55.742+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T04:00:16.632398+00:00 [queued]>
[2024-11-20T11:07:55.743+0700] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-20T11:07:55.772+0700] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_twitter_task> on 2024-11-20 04:00:16.632398+00:00
[2024-11-20T11:07:55.795+0700] {logging_mixin.py:190} WARNING - /home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=148982) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-20T11:07:55.799+0700] {standard_task_runner.py:72} INFO - Started process 149125 to run task
[2024-11-20T11:07:55.798+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'scrape_twitter', 'scrape_twitter_task', 'manual__2024-11-20T04:00:16.632398+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/scrape_twitter_dag.py', '--cfg-path', '/tmp/tmpqn7h5n_4']
[2024-11-20T11:07:55.801+0700] {standard_task_runner.py:105} INFO - Job 33: Subtask scrape_twitter_task
[2024-11-20T11:07:56.232+0700] {task_command.py:467} INFO - Running <TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T04:00:16.632398+00:00 [running]> on host fabian4819-VirtualBox
[2024-11-20T11:07:56.536+0700] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrape_twitter' AIRFLOW_CTX_TASK_ID='scrape_twitter_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T04:00:16.632398+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T04:00:16.632398+00:00'
[2024-11-20T11:07:56.539+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T11:07:56.540+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T11:07:56.540+0700] {logging_mixin.py:190} INFO - Current task name:scrape_twitter_task state:running start_date:2024-11-20 04:07:55.718959+00:00
[2024-11-20T11:07:56.540+0700] {logging_mixin.py:190} INFO - Dag name:scrape_twitter and current dag run status:running
[2024-11-20T11:07:56.542+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T11:08:28.495+0700] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow/dags/scrape_twitter_dag.py", line 40, in run_scrape_twitter
    scrape_twitter(search_term)  # Panggil fungsi dari scrapping-twitter.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/notebooks/scrapping-twitter.py", line 47, in scrape_twitter
    driver.get(search_url)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 389, in get
    self.execute(Command.GET, {"url": url})
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=130.0.6723.116)
Stacktrace:
#0 0x6470f96cb1ca <unknown>
#1 0x6470f91f9f60 <unknown>
#2 0x6470f91f2161 <unknown>
#3 0x6470f91e2948 <unknown>
#4 0x6470f91e465a <unknown>
#5 0x6470f91e2bea <unknown>
#6 0x6470f91e24eb <unknown>
#7 0x6470f91e2411 <unknown>
#8 0x6470f91e050c <unknown>
#9 0x6470f91e0b5a <unknown>
#10 0x6470f91fc809 <unknown>
#11 0x6470f9288f65 <unknown>
#12 0x6470f9269d32 <unknown>
#13 0x6470f92882f7 <unknown>
#14 0x6470f9269ad3 <unknown>
#15 0x6470f9238b6f <unknown>
#16 0x6470f9239b8e <unknown>
#17 0x6470f969931f <unknown>
#18 0x6470f969d442 <unknown>
#19 0x6470f9687827 <unknown>
#20 0x6470f969dbc1 <unknown>
#21 0x6470f966e68e <unknown>
#22 0x6470f96b9998 <unknown>
#23 0x6470f96b9b9a <unknown>
#24 0x6470f96c9e78 <unknown>
#25 0x7b8263522ac3 <unknown>

[2024-11-20T11:08:28.666+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T11:08:28.672+0700] {logging_mixin.py:190} INFO - Task start:2024-11-20 04:07:55.718959+00:00 end:2024-11-20 04:08:28.660593+00:00 duration:32.941634
[2024-11-20T11:08:28.680+0700] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_twitter_task> dag:<DAG: scrape_twitter> dagrun:<DagRun scrape_twitter @ 2024-11-20 04:00:16.632398+00:00: manual__2024-11-20T04:00:16.632398+00:00, state:running, queued_at: 2024-11-20 04:00:16.710528+00:00. externally triggered: True>
[2024-11-20T11:08:28.683+0700] {logging_mixin.py:190} INFO - Failure caused by Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=130.0.6723.116)
Stacktrace:
#0 0x6470f96cb1ca <unknown>
#1 0x6470f91f9f60 <unknown>
#2 0x6470f91f2161 <unknown>
#3 0x6470f91e2948 <unknown>
#4 0x6470f91e465a <unknown>
#5 0x6470f91e2bea <unknown>
#6 0x6470f91e24eb <unknown>
#7 0x6470f91e2411 <unknown>
#8 0x6470f91e050c <unknown>
#9 0x6470f91e0b5a <unknown>
#10 0x6470f91fc809 <unknown>
#11 0x6470f9288f65 <unknown>
#12 0x6470f9269d32 <unknown>
#13 0x6470f92882f7 <unknown>
#14 0x6470f9269ad3 <unknown>
#15 0x6470f9238b6f <unknown>
#16 0x6470f9239b8e <unknown>
#17 0x6470f969931f <unknown>
#18 0x6470f969d442 <unknown>
#19 0x6470f9687827 <unknown>
#20 0x6470f969dbc1 <unknown>
#21 0x6470f966e68e <unknown>
#22 0x6470f96b9998 <unknown>
#23 0x6470f96b9b9a <unknown>
#24 0x6470f96c9e78 <unknown>
#25 0x7b8263522ac3 <unknown>
[2024-11-20T11:08:28.687+0700] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=scrape_twitter, task_id=scrape_twitter_task, run_id=manual__2024-11-20T04:00:16.632398+00:00, execution_date=20241120T040016, start_date=20241120T040755, end_date=20241120T040828
[2024-11-20T11:08:28.745+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T11:08:28.746+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 33 for task scrape_twitter_task (Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=130.0.6723.116)
Stacktrace:
#0 0x6470f96cb1ca <unknown>
#1 0x6470f91f9f60 <unknown>
#2 0x6470f91f2161 <unknown>
#3 0x6470f91e2948 <unknown>
#4 0x6470f91e465a <unknown>
#5 0x6470f91e2bea <unknown>
#6 0x6470f91e24eb <unknown>
#7 0x6470f91e2411 <unknown>
#8 0x6470f91e050c <unknown>
#9 0x6470f91e0b5a <unknown>
#10 0x6470f91fc809 <unknown>
#11 0x6470f9288f65 <unknown>
#12 0x6470f9269d32 <unknown>
#13 0x6470f92882f7 <unknown>
#14 0x6470f9269ad3 <unknown>
#15 0x6470f9238b6f <unknown>
#16 0x6470f9239b8e <unknown>
#17 0x6470f969931f <unknown>
#18 0x6470f969d442 <unknown>
#19 0x6470f9687827 <unknown>
#20 0x6470f969dbc1 <unknown>
#21 0x6470f966e68e <unknown>
#22 0x6470f96b9998 <unknown>
#23 0x6470f96b9b9a <unknown>
#24 0x6470f96c9e78 <unknown>
#25 0x7b8263522ac3 <unknown>
; 149125)
Traceback (most recent call last):
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow/dags/scrape_twitter_dag.py", line 40, in run_scrape_twitter
    scrape_twitter(search_term)  # Panggil fungsi dari scrapping-twitter.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/notebooks/scrapping-twitter.py", line 47, in scrape_twitter
    driver.get(search_url)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 389, in get
    self.execute(Command.GET, {"url": url})
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=130.0.6723.116)
Stacktrace:
#0 0x6470f96cb1ca <unknown>
#1 0x6470f91f9f60 <unknown>
#2 0x6470f91f2161 <unknown>
#3 0x6470f91e2948 <unknown>
#4 0x6470f91e465a <unknown>
#5 0x6470f91e2bea <unknown>
#6 0x6470f91e24eb <unknown>
#7 0x6470f91e2411 <unknown>
#8 0x6470f91e050c <unknown>
#9 0x6470f91e0b5a <unknown>
#10 0x6470f91fc809 <unknown>
#11 0x6470f9288f65 <unknown>
#12 0x6470f9269d32 <unknown>
#13 0x6470f92882f7 <unknown>
#14 0x6470f9269ad3 <unknown>
#15 0x6470f9238b6f <unknown>
#16 0x6470f9239b8e <unknown>
#17 0x6470f969931f <unknown>
#18 0x6470f969d442 <unknown>
#19 0x6470f9687827 <unknown>
#20 0x6470f969dbc1 <unknown>
#21 0x6470f966e68e <unknown>
#22 0x6470f96b9998 <unknown>
#23 0x6470f96b9b9a <unknown>
#24 0x6470f96c9e78 <unknown>
#25 0x7b8263522ac3 <unknown>

[2024-11-20T11:08:28.847+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T11:08:28.949+0700] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T11:08:28.955+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
